#!/usr/bin/env bash

set -x

# ====== Variables =============================

declare -A gaps
declare -A color

gaps["top"]="10"
gaps["bottom"]="10"
gaps["left"]="10"
gaps["right"]="10"
gaps["inner"]="10"

color["focused"]="0xE0808080"
color["normal"]="0x00010101"
color["preselect"]="0xE02d74da"

spaces_refresh_command="sketchybar --trigger workspace_change"

# ===== Loading Scripting Additions ============

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# ===== Tiling setting =========================

yabai -m config layout bsp
yabai -m config window_placement second_child

yabai -m space 1 --display 1 --label 1
yabai -m space 2 --display 1 --label 2
yabai -m space 3 --display 1 --label 3
yabai -m space 4 --display 2 --label 4
yabai -m space 5 --display 2 --label 5
yabai -m space 6 --display 2 --label 6

yabai -m config external_bar all:37:0

yabai -m config top_padding "${gaps["top"]}"
yabai -m config bottom_padding "${gaps["bottom"]}"
yabai -m config left_padding "${gaps["left"]}"
yabai -m config right_padding "${gaps["right"]}"
yabai -m config window_gap "${gaps["inner"]}"

yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m config insert_feedback_color "${color["preselect"]}"

# window shadows only for floating windows
yabai -m config window_shadow float
yabai -m config window_animation_duration 0.00
yabai -m config window_animation_easing easeOutExpo

yabai -m config focus_follows_mouse autoraise

# app rules

# float system preferences
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="^Steam$" manage=off
yabai -m rule --add app="^IINA$" manage=off
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m rule --add title="^music~kew$" sticky=on

# show digital colour meter topmost and on all spaces
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on
yabai -m rule --add app="^Music$" sticky=off manage=off
yabai -m rule --add app="^Music MiniPlayer$" sticky=off manage=off
yabai -m rule --add app="^Finder$" manage=off

# yabai -m signal --add event=display_changed action="${spaces_refresh_command}"
# yabai -m signal --add event=space_changed action="${spaces_refresh_command}"
# yabai -m signal --add event=system_woke action="sleep 2; sketchybar --reload"
