# ~/.config/starship.toml

# Use custom format
#format = """
#[┌────](bold black)$time$username$directory$git_branch$git_status$go$python$cmd_duration
#[└─](bold black)$character"""

format = """
(bold white)$username$directory(bold white)$character"""


# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10


# Disable the blank line at the start of the prompt
add_newline = false

[character]
success_symbol = "[❯](bold white)"
error_symbol = "[? ❯](bold white)"


[time]
disabled = false
format = '[\[$time\]](white) '
time_format = "%T"
utc_time_offset = "+7"

[username]
style_user = "white bold"
style_root = "white bold"
format = "[$user]($style) "
disabled = false
show_always = true

[cmd_duration]
min_time = 100
format = "underwent [$duration](bold white)"

[directory]
style = "white"
